### ISSUE TITLE
Todo List - prep re:publica

### ISSUE THREAD

**Issue by schub** [ZusammenPlayer/zp-hub#12]
- [x] 3 Raspi mit player images
- [x] mvp vom Hub
- [x] mock data structure + content
- [x] test the whole setup
- [x] prepare slideshow
- [x] prepare intro for Dr. Kaletta
